# Usa a imagem oficial mais recente do Node.js LTS
FROM node:22

# Define o diretório de trabalho dentro do container
WORKDIR /app

# Copia apenas os arquivos necessários para instalar as dependências
COPY package.json ./

# Instala as dependências de forma otimizada
RUN npm install --omit=dev --legacy-peer-deps

# Copia o restante do código do projeto
COPY . .

# Garante que as variáveis de ambiente do .env sejam carregadas
ENV NODE_ENV=production

# Expõe a porta da aplicação (ajuste conforme necessário)
EXPOSE 3000

# Inicia a aplicação com Prisma Migration
CMD ["sh", "-c", "npx prisma migrate deploy && npm start"]
