version: '3.8'

services:
  database:
    image: postgres:15
    container_name: postgres_db
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: portfolio
    restart: always
    depends_on:
      - database
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://admin:admin123@database:5432/meu_banco"

volumes:
  pg_data:
